---

- name: Add the official nginx repo to our base image
  copy:
    content: "{{ lookup('file', 'nginx.repo') }}"
    dest: "/etc/yum.repos.d/nginx.repo"
    remote_src: true

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Ensure our service is stopped
  service:
    name: nginx
    state: stopped
    enabled: true

