---


- name: Get oracle jdk
  aws_s3:
    bucket: "{{ artifact_bucket }}"
    object: "/alfresco/jdk-8u181-linux-x64.rpm"
    dest: "/tmp/jdk-8u181-linux-x64.rpm"
    mode: get

- name: Install oracle java
  yum:
    name: /tmp/jdk-8u181-linux-x64.rpm
    state: present

- name: Install/upgrade the epel repo from remote
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest

- name: Update our system
  yum:
    name: '*'
    state: latest

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ alfresco_vars.packages }}"

- name: Clean up
  file:
    path: /tmp/jdk-8u181-linux-x64.rpm
    state: absent

